### ISSUE TITLE
hydra-kernel package.yaml missing SHA dependency: standalone kernel fails to compile (verify-distribution step 11)

### ISSUE THREAD

**Issue by joshsh** [CategoricalData/hydra#542]
## Symptom

CI step 11 "Verify Haskell distribution self-containment" (\`heads/haskell/bin/verify-distribution.sh\`) fails on main after #524 landed:

\`\`\`
Hydra/Overlay/Haskell/Lib/Hashing.hs:7:1: error: [GHC-87110]
    Could not load module 'Data.Digest.Pure.SHA'.
\`\`\`

## Root cause

#524's hashing overlay (\`overlay/haskell/hydra-kernel/.../Lib/Hashing.hs\`) imports \`Data.Digest.Pure.SHA\` (the \`SHA\` Hackage package). \`SHA\` is declared in \`heads/haskell/package.yaml\` (head machinery) but was NOT added to \`EXTERNAL_DEPS["hydra-kernel"]\` in \`bin/lib/generate-haskell-package-build.py\`, so the generated/tracked \`dist/haskell/hydra-kernel/package.yaml\` omits it. The kernel therefore cannot compile as a STANDALONE published package.

## Why it wasn't caught pre-merge

Routine \`sync.sh\` builds the kernel only as a source-dir of the head (where \`SHA\` is on the head's dep list), never standalone. Only \`verify-distribution.sh\` (a CI-only step) builds each per-package distribution in isolation. Same class as the #416 F2 published-host seam, but affecting a **dependency declaration** rather than a module.

## Fix

Add \`SHA >= 1.6.4 && < 1.7\` to \`EXTERNAL_DEPS["hydra-kernel"]\` and regenerate the tracked package.yaml files; verify with \`verify-distribution.sh\` (not just sync.sh). Audit whether other packages copying the kernel runtime (hydra-jvm/java/python) also import SHA via their overlays and need the same.

Relates to #524.

**Comment by joshsh** [comment]
Fixed on main by 93067a1462 (staging coordinator arrived at the identical fix independently — added SHA >= 1.6.4 && < 1.7 to EXTERNAL_DEPS["hydra-kernel"]). Closing as resolved. CI on the fix (run 28696382283) validating now.
