### ISSUE TITLE
Java coder: emit explicit type arguments on PersistentMap.ofEntries (and siblings) for non-empty values

### ISSUE THREAD

**Issue by joshsh** [CategoricalData/hydra#394]
# Java coder: emit explicit type arguments on PersistentMap.ofEntries (and Map.of/Maybe/Either/Pair siblings) for non-empty values

## Summary

The Java coder's `Term.MAP` (and likely `Term.LIST`, `Term.MAYBE`, etc.)
emission produces deeply-nested varargs constructions
(`PersistentMap.ofEntries(Map.entry(k1,v1), Map.entry(k2,v2), …)`).
With enough entries and enough nesting, Java 11.x javac (verified failing
on Temurin **11.0.31**, passing on **11.0.19**) cannot infer the
`<K, V>` type parameters from target context, even though the surrounding
method declaration provides them.

CI is currently pinned to Temurin 11.0.19 as a workaround
(`.github/workflows/ci.yml`).
This issue tracks the proper fix in the Java coder.

## Repro

After commit `7a3df0247e` (May 23, part of #156) added
`Hydra.Sources.Kernel.Types.Typing.module_` to `bootstrapTypeModules`,
`dist/java/hydra-kernel/src/main/java/hydra/json/Bootstrap.java`'s
`typesByName()` method emits a 94-entry `PersistentMap.ofEntries(...)` call
whose values are deeply-annotated `Type` constructions. javac on Temurin
11.0.31 fails with:

```
Bootstrap.java:11: error: incompatible types: inference variable K#1
  has incompatible bounds
    return hydra.util.PersistentMap.ofEntries(...)
  equality constraints: Name,V#1,V#2,...
  lower bounds: Annotated,Name
```

The same source compiles on Temurin 11.0.19 (and presumably 17+, though
not verified). Pre-#156 the map had 83 entries, just under the inference
cliff.

## Why my first fix attempt didn't work

The natural fix is to emit `PersistentMap.<Name, Type>ofEntries(...)` —
explicit type arguments make inference unnecessary. The non-empty `Term.MAP`
field of `encodeTermInternal` in
`packages/hydra-java/src/main/java/hydra/sources/java/Coder.java` already
has *infrastructure* for typed emission: when `tyapps` (the curried
`Term.TypeApplication` chain captured during recursion) is non-empty, it
calls `methodInvocationStaticWithTypeArgs(..., targs, pairExprs)`.

But `tyapps` is empty for the `typesByName` Bootstrap term. The term is a
`TermAnnotated { body = TermMap, annotation = description }` —
no `TypeApplication` wrapping. So the encoder takes the bare-emit branch.

I tried extending the bare branch to call `hydra.checking.typeOfTerm(cx, g, term)`
and decompose the result as `Type.MAP(MapType)`, then encode K/V as
`TypeArgument.REFERENCE` entries. The change was confirmed to land in the
regenerated `coder.json` (new variable names `inferredTyp/Mt/JK/JV`
present), but the regenerated `Bootstrap.java` was unchanged — meaning
the encoder still didn't reach the new code path at this site. Possible
reasons (not yet confirmed):

1. The encoder strips the `TermAnnotated` and recurses through
   `encodeTermInternal` with `term = TermAnnotated.body` not the original
   term, so `typeOfTerm(term)` is being called on the *inner* TermMap
   without the description annotation. In principle that should still
   produce `Type.MAP`.
2. `typeOfTerm` may return `Type.APPLICATION(Type.APPLICATION(Type.MAP, K), V)`
   for an applied-type variant rather than the direct `Type.MAP` variant,
   making the `field(Type.MAP, ...)` case miss.
3. `typeOfTerm` may return `Left` (failure) for this synthetic term, in
   which case the whole `Eithers.bind` propagates failure — yet Bootstrap.java
   still got emitted with the bare form, suggesting the surrounding encode
   has an error-recovery path that falls back to a different emission.

The investigation cycle is expensive: each test requires regenerating the
Java DSL via `bin/generate-hydra-java-from-java.sh` (~30 min per the #372
self-host pathology) then re-emitting Bootstrap.java.

## Proposed approach

The cleanest fix is probably **higher up the chain**, in `encodeTermDefinition`:
when the term's declared signature is a concrete `Type.MAP` (or list/maybe/either/pair),
push synthetic `Type.APPLICATION(Type.APPLICATION(Type.MAP, K), V)` wrappers onto
the term as `Term.TypeApplication` nodes before calling `encodeTermInternal`. That
populates `tyapps` so the existing typed-emit code paths fire naturally without
needing duplicated logic in each `Term.MAP`/`Term.LIST`/etc. branch.

Alternative: extend `encodeTerm` (the entry point that currently passes
`tyapps = list()`) to inspect the term's annotated type and seed `tyapps`
from that.

## Workaround in place

`.github/workflows/ci.yml` Java tests job pins:

```yaml
java-version: '11.0.19'
```

This will need to be reverted once the coder-level fix lands.

## Related

- #156 (added `Typing.module_` to bootstrapTypeModules, tipping count past cliff)
- #344 (Java self-host: changes here go through the long Phase 5 regen path)
- #372 (Java self-host inference exponential cost — slows each iteration of this fix)
